#!/usr/bin/env node
const http = require('http');
const fs = require('fs');
const mime = require('mime');
const documentRoot = './';
const server = http.createServer(function (req, res) {
  const url = (req.url == "/") ? "/index.html" : req.url;
  const file = documentRoot + url;
  console.log(url);
  fs.readFile(file, function (err, data) {
    data = (err) ? '<p>404</p>' : data;
    res.setHeader("Content-Type", mime.lookup(url));
    res.write(data);
    res.end();
  });
}).listen(8080);

console.log('http://localhost:8080/');
